from typing import Protocol


class PolicyRepository(Protocol):
    async def search(self, tenant_id: str, query: str, limit: int) -> list: ...
    async def get_by_code(self, tenant_id: str, code: str): ...
class ReviewRepository(Protocol):
    async def get(self, tenant_id: str, review_id: str): ...
    async def add(self, review): ...
    async def save(self, review): ...
