from typing import Protocol, Any
from uuid import UUID
from app.domain.models import Review, Evidence

class ReviewRepository(Protocol):
    async def add(self, review: Review) -> None: ...
    async def get(self, tenant_id: str, review_id: UUID) -> Review | None: ...
    async def save(self, review: Review) -> None: ...

class EvidenceRepository(Protocol):
    async def search(self, tenant_id: str, query: str, limit: int = 8) -> list[Evidence]: ...

class ResearchWorkflow(Protocol):
    async def run(self, review: Review) -> dict[str, Any]: ...
    async def resume(self, review: Review, decision: str, comment: str, reviewer_id: str) -> dict[str, Any]: ...
