from typing import Protocol, Any
from uuid import UUID
from app.domain.models import Review, Evidence

class ReviewRepository(Protocol):
    async def add(self, review: Review, idempotency_key: str) -> bool: ...
    async def get(self, tenant_id: str, review_id: UUID) -> Review | None: ...
    async def save(self, review: Review, expected_version: int | None = None) -> None: ...

class EvidenceRepository(Protocol):
    async def search(self, tenant_id: str, query: str, limit: int) -> list[Evidence]: ...

class AuditRepository(Protocol):
    async def append(self, tenant_id: str, actor_id: str, action: str, resource_id: str, details: dict) -> None: ...

class CheckpointRepository(Protocol):
    async def save(self, review_id: UUID, node: str, state: dict[str, Any]) -> None: ...

class ResearchWorkflow(Protocol):
    async def run(self, review: Review) -> dict[str, Any]: ...
